twilio.property.account_sid=AC80c286a21259ebf4d9f506f89a924325
twilio.property.auth_token=54330f3029687cbe477e78f462cd4756
twilio.property.sending_phone_number=12562903806
infobip.property.api_key=3ba8d7d69996948b251a3ee4b5df03eb-f9df15b8-f782-4586-8c62-16be1760f31d
infobip.property.base_url=https://mmmy96.api.infobip.com/sms/2/text/advanced
#spring.profiles.active=cloud
server.port=8011
#server.port=8044
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:192.168.100.25}:3306/team_dream
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/team_dream
#spring.datasource.username=testStage
spring.datasource.username=root
#spring.datasource.password=test
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver